INSERT INTO tbl_pizzas (Sabor, Ingredientes, Preco, Id_Receita, Id_Pizzayollo) VALUES
('Pizza de Pepperoni', 'molho de tomate,queijo mozarela,pepperoni fatiado', 25.00, 1, 1),
('Pizza Margherita', 'molho de tomate,queijo mozarela,manjericão fresco', 22.00, 2, 2),
('Pizza Quatro Queijos', 'molho de tomate,queijo mozarela,queijo gorgonzola,queijo parmesão,queijo provolone', 27.00, 3, 3),
('Pizza Calabresa', 'molho de tomate,queijo mozarela,calabresa fatiada,cebola fatiada', 26.00, 4, 4),
('Pizza Frango com Catupiry', 'molho de tomate,queijo mozarela,frango desfiado,catupiry', 28.00, 5, 5),
('Pizza Portuguesa', 'molho de tomate,queijo mozarela,presunto,cebola,ovos,azeitonas,tomate', 27.00, 6, 6),
('Pizza Marguerita', 'molho de tomate,queijo mozarela,tomate,manjericão', 22.00, 7, 7),
('Pizza Bacon', 'molho de tomate,queijo mozarela,bacon fatiado', 25.00, 8, 8),
('Pizza Vegana', 'molho de tomate,queijo vegano,legumes variados', 28.00, 9, 9),
('Pizza Carbonara', 'molho branco,queijo mozarela,bacon,ovos', 27.00, 10, 10),
('Pizza de Frango com Requeijão', 'molho de tomate,queijo mozarela,frango desfiado,requeijão cremoso', 28.00, 11, 11),
('Pizza de Margherita', 'molho de tomate,queijo mozarela,manjericão,tomate fresco', 23.00, 12, 12),
('Pizza Napolitana', 'molho de tomate,queijo mozarela,aliche,azeitonas pretas,alho', 27.00, 13, 13),
('Pizza Atum', 'molho de tomate,queijo mozarela,atum,cebola,azeitonas', 26.00, 14, 14),
('Pizza de Camarão', 'molho de tomate,queijo mozarela,camarão,catupiry', 29.00, 15, 15),
('Pizza Vegetariana', 'molho de tomate,queijo mozarela,brócolis,champignon,pimentão,cebola,milho', 27.00, 16, 16),
('Pizza Siciliana', 'molho de tomate,queijo mozarela,linguiça calabresa,tomate,azeitonas', 28.00, 17, 17),
('Pizza de Rúcula com Tomate Seco', 'molho de tomate,queijo mozarela,rúcula,tomate seco', 25.00, 18, 18),
('Pizza de Quatro Estações', 'molho de tomate,queijo mozarela,presunto,champignon,pimentão,cebola', 27.00, 19, 19),
('Pizza de Banana com Chocolate', 'chocolate ao leite,banana,canela', 22.00, 20, 20),
('Pizza de Frutos do Mar', 'molho de tomate,queijo mozarela,lula,camarão,mariscos', 30.00, 21, 21),
('Pizza Dois Queijos', 'molho de tomate,queijo mozarela,queijo gorgonzola', 26.00, 22, 22),
('Pizza de Chocolate com Morango', 'chocolate ao leite,morangos frescos', 23.00, 23, 23),
('Pizza de Alho', 'molho de tomate,queijo mozarela,alho frito', 24.00, 24, 24),
('Pizza de Presunto Parma com Rúcula', 'molho de tomate,queijo mozarela,presunto parma,rúcula', 25.00, 25, 25),
('Pizza de Escarola com Bacon', 'molho de tomate,queijo mozarela,escarola refogada,bacon', 26.00, 26, 26),
('Pizza de Cheddar com Bacon', 'molho de tomate,queijo cheddar,bacon', 25.00, 27, 27),
('Pizza de Chocolate com Banana', 'chocolate ao leite,banana', 21.00, 28, 28),
('Pizza de Brócolis com Bacon', 'molho de tomate,queijo mozarela,brócolis,bacon', 24.00, 29, 29),
('Pizza de Cogumelos', 'molho de tomate,queijo mozarela,cogumelos variados', 23.00, 30, 30);
SELECT * FROM tbl_pizzas;